### ISSUE TITLE
Unable to download files from blob

### ISSUE THREAD

**Issue by VarshneyNaupada** [seguler/static-website-blob-browser#5]
Hi Team,

I am unable to download the files from the static website. It is listing the blobs but not able to download.

**Comment by thetablebird** [comment]
I ran into this issue after changing the container in the index.js file. The links do not update correctly and try to pull from the Primary Endpoint location ($web)  rather than the container that's being listed.

Here's how I resolved it. Preface, I'm not a developer, just a hack.

In the index.js file, add a constant that contains the link of your container in the section where you define your account and container. The URL will be something like the example below.

`// Account name, and the container to list from`
`const account = 'yourstorageaccount'`
`const container = 'yourblobcontainer'`
`const containerlink = 'https://yourstorageaccount.blob.core.windows.net/yourblobcontainer/'`

Then in the `renderLink(blobName)` section of the index.js file, replace the line
`link = "/" + blobName` 
with 
`link= "containerlink" + blobName` 

Save index.js, rebuild the React app and republish the static webpage based on the original instructions. You should be able to download your listed blobs after this.

**Comment by Peiprjs** [comment]
@thetablebird so should containerlink be a string or a variable?
